services:
  miniserve-secret:
    image: svenstaro/miniserve:latest
    container_name: miniserve-secret
    restart: unless-stopped
    ports:
      - "8097:8080"
    volumes:
      - /mnt/hdd_primary/secret:/data
    command: >
      /data
      --auth admin:admin
      --dirs-first
      --title "Secret Archive"
