services:
  gluetun:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    env_file:
      - /home/pi/qbittorrent/.env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=France
      - TZ=Europe/Paris
      # CHANGE 1: Turn off DoT (High overhead) and use standard DNS
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
      # CHANGE 2: Force MTU on the interface level, not just WireGuard
      - VPN_INTERFACE_MTU=1280
      - WIREGUARD_MTU=1280
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off


    volumes:
      - /home/pi/qbittorrent/gluetun:/gluetun

    # Publish qBittorrent ports here (since qbit shares this network)
    ports:
      - 9091:9091           # qBittorrent
      - 6881:6881
      - 6881:6881/udp
      - 5800:5800           # Firefox noVNC UI


    restart: unless-stopped

  firefox:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: jlesage/firefox:latest
    container_name: firefox
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started
    environment:
      - TZ=Europe/Paris
      - USER_ID=1000
      - GROUP_ID=1000
      - DARK_MODE=1
      - ENABLE_CJK_FONT=0
    volumes:
      - /home/pi/qbittorrent/firefox:/config
      - /home/pi/qbittorrent/qbit_watch:/config/downloads   # <— new: Firefox saves here
      - /dev/shm:/dev/shm
    shm_size: "1gb"
    restart: unless-stopped

  qbittorrent:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=9091
      - UMASK=002
    volumes:
      - /home/pi/qbittorrent/config:/config
      - /mnt/hdd_primary/media/film:/downloads/film
      - /mnt/hdd_primary/media/serie:/downloads/serie
      - /mnt/ssd_primary/public_share/torrent:/downloads/torrent
      - /mnt/ssd_crucial/media:/downloads/media
      - /home/pi/qbittorrent/qbit_watch:/watch              # <— new: qBittorrent watch
    restart: unless-stopped
