services:
  gluetun:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    env_file:
      - /home/pi/qbittorrent/.env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=France
      - TZ=Europe/Paris
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
      - VPN_INTERFACE_MTU=1280
      - WIREGUARD_MTU=1280
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
    volumes:
      - /home/pi/qbittorrent/gluetun:/gluetun
    ports:
      - 9091:9091           # qBittorrent
      - 6881:6881
      - 6881:6881/udp
      - 5800:5800           # Firefox noVNC UI
    restart: unless-stopped

  firefox:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: jlesage/firefox:latest
    container_name: firefox
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started
    environment:
      - TZ=Europe/Paris
      - USER_ID=1000
      - GROUP_ID=1000
      - DARK_MODE=1
      - ENABLE_CJK_FONT=0
      # CORRECTION : On retire VNC_LISTENING_PORT qui créait le conflit
      # On garde la résolution basse pour économiser la RAM
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
      # On s'assure que l'interface web écoute bien sur 5800
      - WEB_LISTENING_PORT=5800
    volumes:
      - /home/pi/qbittorrent/firefox:/config
      - /home/pi/qbittorrent/qbit_watch:/config/downloads
      - /dev/shm:/dev/shm
    # On garde l'optimisation RAM
    shm_size: "512m"
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1.50'
    restart: unless-stopped

  qbittorrent:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=9091
      - UMASK=002
      # OPTIMIZATION 3: Limit qBittorrent internal cache
    volumes:
      - /home/pi/qbittorrent/config:/config
      - /mnt/hdd_primary/media/film:/downloads/film
      - /mnt/hdd_primary/media/serie:/downloads/serie
      - /mnt/ssd_primary/public_share/torrent:/downloads/torrent
      - /mnt/ssd_crucial/media:/downloads/media
      - /home/pi/qbittorrent/qbit_watch:/watch
    deploy:
      resources:
        limits:
          memory: 512M    # qBittorrent shouldn't need more than this
    restart: unless-stopped
