services:
  webdav-quantum:
      image: ugeek/webdav:arm
      container_name: webdav-quantum-public
      volumes:
          # Note: internal path changes from /data to /media for this image
          - /mnt/ssd_crucial/media/livre/:/media
      ports:
          - "8185:80"
      environment:
          - USERNAME=admin
          - PASSWORD=admin
          - UID=1000   # Match your Filebrowser user
          - GID=1000   # Match your Filebrowser group
          - TZ=Europe/Paris # Optional: Set your timezone
      restart: unless-stopped

  filebrowser-quantum-public:
    image: gtstef/filebrowser:latest
    container_name: filebrowser-quantum-public
    user: "1000:1000"
    volumes:
      - /mnt/ssd_primary/public_share:/srv
      - /mnt/hdd_primary/media:/srv/hdd_primary/media
      - /mnt/ssd_crucial/media:/srv/ssd_crucial/media
      - ./fb-public-quantum-db:/home/filebrowser/data
      - ./config/config-public.yaml:/home/filebrowser/config.yaml
    environment:
      - FB_NOAUTH=true
    ports:
      - "8095:80"
    restart: unless-stopped
