services:
  webdav-quantum:
      image: derkades/webdav
      container_name: webdav-quantum-public
      volumes:
          - /mnt/ssd_crucial/media/livre/:/data
      ports:
          - "8185:80"
      environment:
          USERNAME: admin
          PASSWORD: admin
      restart: unless-stopped

  filebrowser-quantum-public:
    image: gtstef/filebrowser:latest
    container_name: filebrowser-quantum-public
    user: "1000:1000"
    volumes:
      - /mnt/ssd_primary/public_share:/srv
      - /mnt/hdd_primary/media:/srv/hdd_primary/media
      - /mnt/ssd_crucial/media:/srv/ssd_crucial/media
      - ./fb-public-quantum-db:/home/filebrowser/data
      - ./config/config-public.yaml:/config.yaml
    environment:
      - FB_NOAUTH=true    # <--- Add this line
    ports:
      - "8095:80"
    restart: unless-stopped

  filebrowser-quantum-secret:
    image: gtstef/filebrowser:latest
    container_name: filebrowser-quantum-secret
    user: "1000:1000"
    volumes:
      - /mnt/hdd_primary/secret:/srv
      - ./fb-secret-quantum-db:/home/filebrowser/data
      - ./config/config-secret.yaml:/config.yaml
    ports:
      - "8097:80"
    restart: unless-stopped
