version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ./
        target: /config
      - type: bind
        source: /mnt/ssd_crucial/media/livre
        target: /data
    ports:
      - 25600:25600
    user: "1000:1000"
    restart: unless-stopped
