services:
  vikunja:
    image: vikunja/vikunja:latest
    environment:
      VIKUNJA_SERVICE_PUBLICURL: http://100.69.22.42:3456
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: changeme
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: admin
      VIKUNJA_SERVICE_TIMEZONE: Europe/Paris
      # --- SECURITY: DISABLE NEW REGISTRATIONS ---
      # Set this to "false" so no one else can create an account.
      # You must have your account created before setting this!
      VIKUNJA_SERVICE_ENABLEREGISTRATION: "false"

      VIKUNJA_SERVICE_JWTTTL: 31536000

      # GMAIL SETTINGS
      VIKUNJA_MAILER_ENABLED: "true"
      VIKUNJA_MAILER_HOST: smtp.gmail.com
      VIKUNJA_MAILER_PORT: 587
      VIKUNJA_MAILER_SKIPTLSVERIFY: "false"
      VIKUNJA_MAILER_USERNAME: mickael.ramilison@gmail.com
      VIKUNJA_MAILER_PASSWORD: ${VIKUNJA_MAIL_PASSWORD}
      VIKUNJA_MAILER_FROMEMAIL: vikunja@gmail.com
      VIKUNJA_MAILER_AUTHTYPE: login
      VIKUNJA_MAILER_FORCESSL: "false"
      HOME: /tmp
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
    tmpfs:
      - /tmp
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: vikunja
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s
