services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - /home/pi/calibre/config:/config             # bibliothèque Calibre par défaut: /config/Calibre Library
      - /home/pi/calibre/recipes:/recipes           # vos recettes (facultatif)
      - /mnt/hdd_primary/media/livre:/output   # vos EPUB "daily news" générés (facultatif)
    ports:
      - "8080:8080"  # GUI (noVNC/HTTP) - pour config
      - "8981:8181"  # GUI (HTTPS)      - pour config
      - "8881:8081"  # Content server   - OPDS
      - "9090:9090"

    restart: unless-stopped
