title: Pi Home
theme: dark
language: en
layout:
  - Media
  - Productivity
  - Files
  - Infra
providers:
  docker:
    socket: /var/run/docker.sock
favicon: http://100.69.22.42:3000/images/homepage.png
