# 4 januari 2023 om 13:51:25 PST
- datetime:
    text_size: 3xl
    locale: fr
    format:
      timeStyle: medium
      dateStyle: long


- openmeteo:
    label: Paris
    latitude: 48.8566
    longitude: 2.3522
    timezone: Europe/Paris
    units: metric       # Â°C
    cache: 5            # minutes de cache

- glances:
    label: Pi 5
    url: http://100.69.22.42:61208   # <-- PAS de /api/4/status ici
    version: 4                       # obligatoire avec Glances v4
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    expanded: true
